;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        TeX-insert-sub-or-superscript
        comment-dwim-2
        ess-smart-comma
        evil-escape-emacs-state
        evil-insert
        evil-insert-state
        evil-lisp-state-sp-forward-barf-sexp
        evil-lisp-state-sp-forward-slurp-sexp
        evil-lisp-state-wrap
        evil-normal-state
        fill-paragraph
        forward-sexp
        helm-show-kill-ring
        keyboard-escape-quit
        kill-region
        kill-sexp
        lisp-state-forward-symbol
        magit-unstage-item
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-metaright
        org-return-indent
        org-self-insert-command
        org-shiftright
        org-todo
        orgtbl-self-insert-command
        paredit-backward
        paredit-backward-up
        paredit-close-round
        paredit-forward
        paredit-forward-barf-sexp
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-newline
        paredit-open-round
        personal/kill-region-or-backward-word
        shrink-whitespace
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-symbol
        sp-delete-char
        sp-end-of-sexp
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-kill-word
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        comint-previous-input
        elisp-slime-nav-find-elisp-thing-at-point
        helm-M-x
        multiple-cursors/expand-or-mark-next-symbol
        ))
