;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-sub-or-superscript
        evil-insert-state
        evil-lisp-state-sp-forward-barf-sexp
        evil-lisp-state-sp-forward-slurp-sexp
        evil-lisp-state-wrap
        evil-normal-state
        lisp-state-forward-symbol
        org-metaright
        org-self-insert-command
        org-shiftright
        paredit-close-round
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-newline
        paredit-open-round
        sp-backward-kill-word
        sp-backward-symbol
        sp-end-of-sexp
        sp-forward-slurp-sexp
        sp-kill-word
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        elisp-slime-nav-find-elisp-thing-at-point
        evil-escape-emacs-state
        multiple-cursors/expand-or-mark-next-symbol
        ))
