(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(LaTeX-beamer-item-overlay-flag nil)
 '(TeX-master nil)
 '(ac-ignore-case nil)
 '(browse-kill-ring-quit-action (quote save-and-restore))
 '(cluck-fontify-style nil)
 '(cperl-auto-newline nil)
 '(cperl-auto-newline-after-colon nil)
 '(cperl-autoindent-on-semi t)
 '(cperl-continued-statement-offset 0)
 '(cperl-highlight-variables-indiscriminately t)
 '(custom-safe-themes (quote ("6a37be365d1d95fad2f4d185e51928c789ef7a4ccf17e7ca13ad63a8bf5b922f" "756597b162f1be60a12dbd52bab71d40d6a2845a3e3c2584c6573ee9c332a66e" "025354235e98db5e7fd9c1a74622ff53ad31b7bde537d290ff68d85665213d85" "6fe6ab4abe97a4f13533e47ae59fbba7f2919583f9162b440dd06707b01f7794" default)))
 '(ecb-layout-name "left7")
 '(ecb-options-version "2.40")
 '(ecb-primary-secondary-mouse-buttons (quote mouse-1--C-mouse-1))
 '(ecb-show-sources-in-directories-buffer (quote always))
 '(ecb-source-path (quote ("/home/jcp/src/" "/home/jcp/Documents/" "/")))
 '(ecb-windows-width 0.2)
 '(erc-header-line-face-method t)
 '(eshell-cmpl-ignore-case t)
 '(ess-R-font-lock-keywords (quote ((ess-R-fl-keyword:modifiers . t) (ess-R-fl-keyword:fun-defs . t) (ess-R-fl-keyword:keywords . t) (ess-R-fl-keyword:assign-ops . t) (ess-R-fl-keyword:constants . t) (ess-fl-keyword:fun-calls . t) (ess-fl-keyword:numbers . t) (ess-fl-keyword:operators . t) (ess-fl-keyword:delimiters) (ess-fl-keyword:= . t) (ess-R-fl-keyword:F&T . t))))
 '(ess-default-style (quote OWN))
 '(ess-own-style-list (quote ((ess-indent-level . 4) (ess-continued-statement-offset . 4) (ess-brace-offset . 0) (ess-expression-offset . 4) (ess-else-offset . 0) (ess-brace-imaginary-offset . 0) (ess-continued-brace-offset . 0) (ess-arg-function-offset . 2) (ess-close-brace-offset . 0))))
 '(evil-cross-lines t)
 '(evil-default-cursor t)
 '(evil-esc-delay 0)
 '(haskell-program-name "ghci -XTemplateHaskell")
 '(hippie-expand-dabbrev-skip-space t)
 '(inferior-R-font-lock-keywords (quote ((ess-S-fl-keyword:prompt . t) (ess-R-fl-keyword:messages . t) (ess-R-fl-keyword:modifiers . t) (ess-R-fl-keyword:fun-defs . t) (ess-R-fl-keyword:keywords . t) (ess-R-fl-keyword:assign-ops . t) (ess-R-fl-keyword:constants . t) (ess-fl-keyword:matrix-labels . t) (ess-fl-keyword:fun-calls) (ess-fl-keyword:numbers . t) (ess-fl-keyword:operators . t) (ess-fl-keyword:delimiters) (ess-fl-keyword:= . t) (ess-R-fl-keyword:F&T . t))))
 '(jde-global-classpath (quote (".")))
 '(make-backup-files nil)
 '(org-completion-use-ido t)
 '(org-default-notes-file "~/org/captured.org")
 '(org-file-apps (quote ((auto-mode . emacs) ("\\.mm\\'" . default) ("\\.x?html?\\'" . default) ("\\.pdf\\'" . "zathura %s"))))
 '(org-hide-leading-stars t)
 '(org-modules (quote (org-bbdb org-bibtex org-docview org-gnus org-info org-jsinfo org-habit org-irc org-mew org-mhe org-rmail org-vm org-wl org-w3m)))
 '(org-src-fontify-natively t)
 '(pde-abbv-use-snippet nil)
 '(py-electric-colon-active-p t)
 '(quack-fontify-style nil)
 '(quack-programs (quote ("racket" "bigloo" "csi" "csi -hygienic" "gosh" "gsi" "gsi ~~/syntax-case.scm -" "guile" "kawa" "mit-scheme" "mred -z" "mzscheme" "mzscheme -il r6rs" "mzscheme -il typed-scheme" "mzscheme -M errortrace" "mzscheme3m" "mzschemecgc" "rs" "scheme" "scheme48" "scsh" "sisc" "stklos" "sxi")))
 '(quack-remap-find-file-bindings-p nil)
 '(ruby-block-highlight-face (quote fringe))
 '(ruby-block-highlight-toggle (quote overlay))
 '(safe-local-variable-values (quote ((folded-file . t))))
 '(scroll-bar-mode nil)
 '(show-paren-mode t)
 '(slime-complete-symbol-function (quote slime-simple-complete-symbol))
 '(speedbar-use-images t)
 '(tags-revert-without-query t)
 '(tags-table-list nil)
 '(uniquify-buffer-name-style (quote post-forward) nil (uniquify))
 '(user-mail-address "jcpetkovich@gmail.com")
 '(vimpulse-want-C-i-like-Vim nil)
 '(viper-ex-style-motion nil)
 '(viper-fast-keyseq-timeout 0)
 '(w3m-default-display-inline-images t)
 '(x-select-enable-clipboard t)
 '(x-select-enable-primary t)
 '(yas-indent-line (quote auto)))


(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(mumamo-background-chunk-major ((((class color) (min-colors 88) (background dark)) (:background "Black"))) t))

(put 'narrow-to-region 'disabled nil)
(put 'upcase-region 'disabled nil)
(put 'erase-buffer 'disabled nil)
